spring:
  application:
    name: targetprocess-mcp
  main:
    banner-mode: off
    web-application-type: none
  ai:
    mcp:
      server:
        name: targetprocess-mcp-server
        version: 0.0.2
        transport: STDIO

targetprocess:
  baseUrl: ${TARGETPROCESS_BASE_URL:https://your_account.tpondemand.com}
  accessToken: ${TARGETPROCESS_ACCESS_TOKEN:your_api_key}

logging:
  level:
    com.ibm.mcp.targetprocess: DEBUG
    org.springframework.ai.mcp: DEBUG
